### PR TITLE
docs: Add Firefox-specific README for add-on reviewers

### PR DESCRIPTION
**Pull request by jurevans**
Copied from @emccorson https://github.com/anoma/namada-interface/pull/999/files

This PR adds a specific README for reviewers of the Firefox add-on.

Preview: https://github.com/anoma/namada-interface/blob/d27579c88bb9f5a252e819068df5afe5221d0bfd/FIREFOX_README.md

### CODE REVIEW

**Comment by emccorson** [comment]
I forgot to add to the README that we will need to set the chain ID to match whatever we are submitting.

**Comment by euharrison** [comment]
How about saving this on the `apps/extension` folder?

And also adding a reference for it on the main README file?

**Review by euharrison — APPROVED** [review]

**Comment by jurevans** [comment]
> How about saving this on the `apps/extension` folder?
> 
> And also adding a reference for it on the main README file?

Thanks! And done

**Comment by jurevans** [comment]
> I forgot to add to the README that we will need to set the chain ID to match whatever we are submitting.

Thanks! Will do that

**Review by mateuszjasiuk — APPROVED** [review]
LGTM! Hope it helps firefox reviewers 🕯️

**Pull request merged**
