### PR TITLE
feat: Faucet - Make extension connection optional

### PR DESCRIPTION
**Pull request by jurevans**
Users of the faucet app have had issues using it when the accounts they need to fund are generate in the CLI.

This update removes the need to connect the extension to access your accounts, but it is still an option.

### CODE REVIEW

**Review by euharrison — APPROVED** [review]
LGTM! ✅

**Comment by euharrison** [comment]
Thinking loud... we should increase the contrast of the fields

Screenshot 2024-09-13 at 10 34 00

**Comment by mateuszjasiuk** [comment]
Not sure if it's me only but I found hidden message :)
image

**Review by mateuszjasiuk — APPROVED** [review]
LGTM! Works nicely!

**Comment by jurevans** [comment]
> Not sure if it's me only but I found hidden message :)

Good catch! I can fix that

**Pull request merged**
