### PR TITLE
WIP: feat: use enhanced design

### PR DESCRIPTION
**Pull request by RuslanGlaznyov**
## What does this PR do
Implement a new design for the Namada faucet

## Context
1. Community builder @cryptobtcbuyer (CB Discord member) created a new design for a faucet 
https://www.figma.com/file/MpTmPN6A0WLgj0Op8xvQAx/Namada-Faucet-by-cryptobtcbuyer?type=design&node-id=0%3A1&mode=design&t=lxFevWm0BSom96Ic-1
2. `Chris | Head of Art and UX` liked it and asked from community to implement it
 
 PS: Marked this as WIP @cryptobtcbuyer would like to add some fixes 

More context can be found in this discord CB post:
https://discord.com/channels/833618405537218590/1174062025664647300/1174062372634230846

## Externals 
Preview page: https://faucet-namada.pages.dev/

https://github.com/anoma/namada-interface/assets/26277721/250b42b8-55c8-49d5-9581-9ca2bd44c52a

### CODE REVIEW

**Comment by emccorson** [comment]
Thanks for your PR!
The Discord link is not working for me. Could you please let me know where to look for the context on Discord or post it here if possible?

**Comment by RuslanGlaznyov** [comment]
I've asked a HELIAX team member to provide you more context!

**Comment by emccorson** [comment]
Thanks! I've got access to the Discord and some more context about this PR.
For now I will mark this as draft, and when it is ready for review, would you mind un-drafting it and requesting me and most likely @pedrorezende as reviewers please? (Although other team members might end up reviewing it instead.)
Please also rebase to the current `main` just before marking as ready for review.

**Comment by RuslanGlaznyov** [comment]
@emccorson The force pushed by mistake   : ) 
I've created a new PR: https://github.com/anoma/namada-interface/pull/491

**Pull request closed without merging**
